//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchBll.SSOWebService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SSOWebService.PassportServiceSoap")]
    public interface PassportServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSystem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddSystem(string sysName, string sysUrl, string sta, string dep, string ContactPerson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSystemRoles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddSystemRoles(out string msg, System.Guid sysid, string rolename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUsersRoles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddUsersRoles(out string msg, System.Guid roleid, string badge);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelSystemRoles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DelSystemRoles(out string msg, System.Guid roleid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelUsersRoles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DelUsersRoles(out string msg, System.Guid roleid, string badge);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListSystems", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListSystems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListRoles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListRoles(System.Guid sysid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListUserRoles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListUserRoles(System.Guid sysid, string badge);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListUsersByRole", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListUsersByRole(System.Guid roleid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListSysUsers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListSysUsers(System.Guid sysid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAllUser(string site);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserByBadge", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetUserByBadge(string badge);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserEmailByBadge", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetUserEmailByBadge(string badge);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDepcnames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetDepcnames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDepcnamesByCompany", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetDepcnamesByCompany(string company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCompanys", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCompanys();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetUserList(string where, bool allornull, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TokenGetCredence", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable TokenGetCredence(out System.Data.DataTable userRoles, string tokenValue, System.Guid sysID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TokenGetCredence2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TokenGetCredence2(string tokenValue, string sysID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCompletionList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetCompletionList(string prefixText, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCompletionListByLeader", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetCompletionListByLeader(string prefixText, int count, string leader);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidaLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ValidaLogin(out System.Data.DataTable dt, string username, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGroupleaderByDepcname", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetGroupleaderByDepcname(string depcname);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PassportServiceSoapChannel : ArchBll.SSOWebService.PassportServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PassportServiceSoapClient : System.ServiceModel.ClientBase<ArchBll.SSOWebService.PassportServiceSoap>, ArchBll.SSOWebService.PassportServiceSoap {
        
        public PassportServiceSoapClient() {
        }
        
        public PassportServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PassportServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PassportServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PassportServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public bool AddSystem(string sysName, string sysUrl, string sta, string dep, string ContactPerson) {
            return base.Channel.AddSystem(sysName, sysUrl, sta, dep, ContactPerson);
        }
        
        public bool AddSystemRoles(out string msg, System.Guid sysid, string rolename) {
            return base.Channel.AddSystemRoles(out msg, sysid, rolename);
        }
        
        public bool AddUsersRoles(out string msg, System.Guid roleid, string badge) {
            return base.Channel.AddUsersRoles(out msg, roleid, badge);
        }
        
        public bool DelSystemRoles(out string msg, System.Guid roleid) {
            return base.Channel.DelSystemRoles(out msg, roleid);
        }
        
        public bool DelUsersRoles(out string msg, System.Guid roleid, string badge) {
            return base.Channel.DelUsersRoles(out msg, roleid, badge);
        }
        
        public System.Data.DataTable ListSystems() {
            return base.Channel.ListSystems();
        }
        
        public System.Data.DataTable ListRoles(System.Guid sysid) {
            return base.Channel.ListRoles(sysid);
        }
        
        public System.Data.DataTable ListUserRoles(System.Guid sysid, string badge) {
            return base.Channel.ListUserRoles(sysid, badge);
        }
        
        public System.Data.DataTable ListUsersByRole(System.Guid roleid) {
            return base.Channel.ListUsersByRole(roleid);
        }
        
        public System.Data.DataTable ListSysUsers(System.Guid sysid) {
            return base.Channel.ListSysUsers(sysid);
        }
        
        public System.Data.DataTable GetAllUser(string site) {
            return base.Channel.GetAllUser(site);
        }
        
        public System.Data.DataTable GetUserByBadge(string badge) {
            return base.Channel.GetUserByBadge(badge);
        }
        
        public string GetUserEmailByBadge(string badge) {
            return base.Channel.GetUserEmailByBadge(badge);
        }
        
        public System.Data.DataTable GetDepcnames() {
            return base.Channel.GetDepcnames();
        }
        
        public System.Data.DataTable GetDepcnamesByCompany(string company) {
            return base.Channel.GetDepcnamesByCompany(company);
        }
        
        public System.Data.DataTable GetCompanys() {
            return base.Channel.GetCompanys();
        }
        
        public System.Data.DataTable GetUserList(string where, bool allornull, string pwd) {
            return base.Channel.GetUserList(where, allornull, pwd);
        }
        
        public System.Data.DataTable TokenGetCredence(out System.Data.DataTable userRoles, string tokenValue, System.Guid sysID) {
            return base.Channel.TokenGetCredence(out userRoles, tokenValue, sysID);
        }
        
        public System.Data.DataSet TokenGetCredence2(string tokenValue, string sysID) {
            return base.Channel.TokenGetCredence2(tokenValue, sysID);
        }
        
        public string[] GetCompletionList(string prefixText, int count) {
            return base.Channel.GetCompletionList(prefixText, count);
        }
        
        public string[] GetCompletionListByLeader(string prefixText, int count, string leader) {
            return base.Channel.GetCompletionListByLeader(prefixText, count, leader);
        }
        
        public bool ValidaLogin(out System.Data.DataTable dt, string username, string pwd) {
            return base.Channel.ValidaLogin(out dt, username, pwd);
        }
        
        public System.Data.DataTable GetGroupleaderByDepcname(string depcname) {
            return base.Channel.GetGroupleaderByDepcname(depcname);
        }
    }
}
